stagingapp/stagingapp/config/routes.rb
Rails.application.routes.draw do


  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  
  get  '/makeredirect',  to: 'urls#new'
  post '/makeredirect',  to: 'urls#create'  
  
  resources :urls

 
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]
  

  resources :changeplans, only: [:edit, :update]


  resources :subscribers
  

  
  post '/stripe/webhooks', to: "stripe#webhooks"





  
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

stagingapp/stagingapp/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The rewroute site</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

stagingapp/stagingapp/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Rewroute app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
		  
		  
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Your redirections", current_user %></li>
			  <li><%= link_to "Update your profile", edit_user_path(current_user) %></li>
			  

			  <li><%= link_to "Make a redirection", makeredirect_path %></li>
			  
			  
			  
			  
			  
			  <% if subscribed? %>
			    <li><%= link_to "Your subscription", subscriber_path(current_subscriber_id) %></li>
			  <% else %>
			    <li><%= link_to "Subscribe", new_subscriber_path %></li>
				
			  <% end %>
			  
			  <% if subscribed? %>
	            <li><%= link_to "Change payment info", edit_subscriber_path(current_subscriber_id) %></li>
				
				<li><%= link_to "Change plan", edit_changeplan_path(current_subscriber_id) %></li>
			  <% end %>
			  
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

stagingapp/stagingapp/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

stagingapp/stagingapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	
	<%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
	
   <%= tag :meta, :name => "stripe-key", :content => Rails.application.secrets.stripe_publishable_key %>
	
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
	
      <%= yield %>
	  <%= render 'layouts/footer' %>
	  <%= debug(params) if Rails.env.development? %>


    </div>
  </body>
</html>