stagingapp/stagingapp/config/routes.rb
Rails.application.routes.draw do


  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  
  get  '/makeredirect',  to: 'urls#new'
  post '/makeredirect',  to: 'urls#create'  
  
  resources :urls

 
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]
  

  resources :changeplans, only: [:edit, :update]


  resources :subscribers
  

  
  post '/stripe/webhooks', to: "stripe#webhooks"





  
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

stagingapp/stagingapp/app/models/url.rb
class Url < ApplicationRecord
  belongs_to :user
  default_scope -> { order(updated_at: :desc) }
  validates :user_id, presence: true
  validates :source,  presence: true, uniqueness: true
  validates :destination,  presence: true

  
  #add a limit to the length? also the uniqunesse true is a x2 verification on the db and on the view? meh
  #validates :source, presence: true, length: { maximum: 65536 }, uniqueness: true  
  #https://stackoverflow.com/questions/3354330/difference-between-string-and-text-in-rails
end

stagingapp/stagingapp/app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :logged_in_user, only: [:show, :new, :create, :destroy, :edit, :update]
  #can a user create a url for another user? I dont think so but just in case, comment to test later
  before_action :correct_user_url,   only: [:show, :destroy, :edit, :update]

  def show
    @url = current_user.urls.find(params[:id])
  end  
  
  
  
  def new
    @url = current_user.urls.build if logged_in?
	#repetition logged_in already checked with the before action
  end

  def create
	if subscribed?	
		subscriberr = Subscriber.find_by user_id: current_user.id
		if Time.now < subscriberr.subscription_expires_at
		    planid = subscriberr.plan_id
			dis = Plan.find_by id: planid
			if numberofredirects <= dis.maxredirect
				@url = current_user.urls.build(user_params)
				if @url.save
				  flash[:success] = "Url redirection created."
				  redirect_to user_path(current_user)
				else
				  render 'new'
				end				
			else
				flash[:info] = "You've reached your maximum number of redirects."
			end
		else
			flash[:info] = "Your subscription expired, you need to resubscribe."
			redirect_to edit_subscriber_path(current_subscriber_id)		
		end
	else
		if numberofredirects == 0
			@url = current_user.urls.build(user_params)
			if @url.save
			  flash[:success] = "Url redirection created."
			  redirect_to user_path(current_user)
			else
			  render 'new'
			end			
		else
			flash[:info] = "You can create one source->destination mapping maximum, you already have one, if you want more subscribe to a better plan."
			redirect_to user_path(current_user)
		end
	end
  end

  #I dont see why they cant destroy if not subscribed ^^, and number of redirects can only go down so all's good ^^
  def destroy
    @url.destroy
    flash[:success] = "Url redirection deleted."
    redirect_to user_path(current_user)
  end
  
  def edit
    @url = current_user.urls.find(params[:id])
  end

  def update
	if subscribed?	
		subscriberr = Subscriber.find_by user_id: current_user.id
		if Time.now < subscriberr.subscription_expires_at
		    planid = subscriberr.plan_id
			dis = Plan.find_by id: planid
			if numberofredirects <= dis.maxredirect
				@url = current_user.urls.find(params[:id])
				if @url.update_attributes(user_params)
				  # Handle a successful update.
				  flash[:success] = "Url redirection edited"
				  redirect_to user_path(current_user)
				else
				  render 'edit'
				end		
			else
				flash[:info] = "You've reached your maximum number of redirects."
			end
		else
			flash[:info] = "Your subscription expired, you need to resubscribe."
			redirect_to edit_subscriber_path(current_subscriber_id)		
		end
	else
		@url = current_user.urls.find(params[:id])
		if @url.update_attributes(user_params)
		  # Handle a successful update.
		  flash[:success] = "Url redirection edited"
		  redirect_to user_path(current_user)
		else
		  render 'edit'
		end
	end
  end
  
  private

    def user_params
	  params.require(:url).permit(:source, :destination)
    end  
	
    def correct_user_url
      @url = current_user.urls.find_by(id: params[:id])
      redirect_to user_path(current_user) if @url.nil?
    end
	
end

stagingapp/stagingapp/app/views/urls/_url.html.erb
<tr>
  <td class="text"><span><%= url.source %></span></td>
  <td class="text"><span><%= url.destination %></span></td>
  <td><%= url.active %></td>
  <td><%= link_to "View redirection", url_path(url) %></td>
  <td><%= link_to "Edit redirection", edit_url_path(url) %></td>
  <td><%= link_to "delete", url, method: :delete, data: { confirm: "You sure?" } %></td>
</tr>

stagingapp/stagingapp/app/views/urls/edit.html.erb
<% provide(:title, "Edit redirection") %>
<h1>Update your redirection</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@url) do |f| %>
      
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :source %>
      <%= f.text_field :source, class: 'form-control' %>

      <%= f.label :destination %>


      </br>
      <span>Make sure to include http:// or https:// before your destination address.</span>


      <%= f.text_area :destination,  class: 'form-control' %>
	  
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>


  </div>
</div>

stagingapp/stagingapp/app/views/urls/new.html.erb
<% provide(:title, 'Make your redirection') %>
<h1>Make your redirection</h1>

<div class="row justify-content-center">
  <div class="col-md-6">
	<%= form_for(@url, url: makeredirect_path) do |f| %>

      
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :source %>
      <%= f.text_field :source, class: 'form-control' %>

      <%= f.label :destination %>

      </br>
      <span>Make sure to include http:// or https:// before your destination address.</span>
      <%= f.text_field :destination, class: 'form-control' %>
	  
      <%= f.submit "Create my redirection", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

stagingapp/stagingapp/app/views/urls/show.html.erb
<% provide(:title, "My redirection") %>
<div class="row">


<div class="container">
<h3>Your redirection</h3>
<div class="table-responsive">
	<table class="table">
	  <thead class="thead">
		<tr>
		  <th scope="col">source</th>
		  <th scope="col" >destination</th>
		  <th scope="col">active</th>	  
		</tr>
	  </thead>
	  <tbody>
		<tr>
		  <td><%= @url.source %></td>
		  <td><%= @url.destination %></td>
		  <td><%= @url.active %></td>
		</tr>
	  </tbody>
	</table>	  
</div>

</div>


<div class="container">
<h3>DNS entry</h3>
<p>Your DNS entry should look like this below for this redirect.</p>
<div class="table-responsive">



	<table class="table">
	  <thead class="thead">
		<tr>
		  <th scope="col">source domain name</th>
		  <th scope="col" >Destination</th>
		  <th scope="col">Record Type</th>	  
		</tr>
	  </thead>
	  <tbody>
		<tr>
		  <td><%= @url.source %></td>
		  <td>rewroute.com</td>
		  <td>CNAME</td>
		</tr>
	  </tbody>
	</table>	  
</div>

</div>  



</div>